#!/bin/bash
# ============================================================
# NAS 端注册每日 03:00 自动备份任务 (管理员一键工具)
#
# 用法 (在 NAS 上以 root 身份执行一次):
#   sudo /volume3/docker/erp-system/scripts/nas-backup/install_cron.sh
#
# 效果:
#   - 在 /etc/cron.d/erp_daily_backup 写入一条用户级 cron 任务
#   - 每天 03:00 由 crond 调起 backup.sh
#   - 输出同步到 /volume3/docker/erp-system/scripts/nas-backup/logs/cron.log
#   - 不再依赖 DSM Task Scheduler (若 web 端未配置, 也照跑)
#
# 卸载:
#   sudo rm /etc/cron.d/erp_daily_backup
# ============================================================
set -euo pipefail
TARGET="/etc/cron.d/erp_daily_backup"
SCRIPT="/volume3/docker/erp-system/scripts/nas-backup/backup.sh"
LOG_DIR="/volume3/docker/erp-system/scripts/nas-backup/logs"
LOG_FILE="$LOG_DIR/cron.log"

# 必须是 root
[ "$(id -u)" -eq 0 ] || { echo "✗ 需要 root 权限: sudo $0"; exit 1; }

# 健康检查:脚本必须存在
[ -x "$SCRIPT" ] || { echo "✗ 脚本不可执行: $SCRIPT"; exit 1; }
mkdir -p "$LOG_DIR"

# 去重: 如果已存在, 提示用户确认后覆盖
if [ -f "$TARGET" ]; then
    echo "⚠  已存在: $TARGET"
    echo "    将会覆盖现有 cron 配置."
    echo "    如果同时使用 DSM Task Scheduler, 会导致备份双跑!"
    read -p "是否覆盖? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "已取消."
        exit 0
    fi
fi

cat > "$TARGET" <<EOF
# ERP daily backup (generated by install_cron.sh)
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
0 3 * * * root $SCRIPT >> $LOG_FILE 2>&1
EOF
chmod 644 "$TARGET"

echo "✓ 已写入: $TARGET"
echo "  - 时间: 每天 03:00"
echo "  - 命令: $SCRIPT"
echo "  - 日志: $LOG_FILE"
echo ""
echo "卸载: sudo rm $TARGET"
echo "查看日志: tail -f $LOG_FILE"
echo ""
echo "立即跑一次验证: sudo $SCRIPT"
