-- =====================================================================
-- 四、销售管理模块 (sal_*)
-- =====================================================================

-- 4.1  销售订单
DROP TABLE IF EXISTS `sal_order`;
CREATE TABLE `sal_order` (
  `id`              BIGINT        NOT NULL AUTO_INCREMENT,
  `bill_no`         VARCHAR(32)   NOT NULL COMMENT '订单号: SO+yyyyMMdd+0001',
  `bill_date`       DATE          NOT NULL,
  `customer_id`     BIGINT        NOT NULL,
  `customer_name`   VARCHAR(128)  DEFAULT NULL,
  `price_level`     VARCHAR(32)   DEFAULT 'RETAIL',
  `warehouse_id`    BIGINT        NOT NULL,
  `salesman_id`     BIGINT        DEFAULT NULL,
  `salesman_name`   VARCHAR(64)   DEFAULT NULL,
  `order_type`      VARCHAR(32)   DEFAULT 'NORMAL' COMMENT 'NORMAL/URGENT/CONTRACT',
  `pay_type`        VARCHAR(32)   DEFAULT 'CASH',
  `currency`        VARCHAR(8)    DEFAULT 'CNY',
  `exchange_rate`   DECIMAL(12,6) DEFAULT 1.000000,
  `total_qty`       DECIMAL(18,4) DEFAULT 0,
  `total_amount`    DECIMAL(18,4) DEFAULT 0,
  `discount_rate`   DECIMAL(8,4)  DEFAULT 1.0000 COMMENT '整单折扣',
  `discount_amount` DECIMAL(18,4) DEFAULT 0,
  `tail_amount`     DECIMAL(18,4) DEFAULT 0 COMMENT '抹零',
  `tax_amount`      DECIMAL(18,4) DEFAULT 0,
  `total_amount_tax` DECIMAL(18,4) DEFAULT 0,
  `received_amount` DECIMAL(18,4) DEFAULT 0,
  `delivery_date`   DATE          DEFAULT NULL,
  `address`         VARCHAR(255)  DEFAULT NULL,
  `phone`           VARCHAR(20)   DEFAULT NULL,
  `bill_status`     VARCHAR(32)   DEFAULT 'DRAFT' COMMENT 'DRAFT/CHECKED/PICKING/FINISHED/CLOSED/CANCELLED',
  `source_bill_id`  BIGINT        DEFAULT NULL COMMENT '来源报价单ID',
  `remark`          VARCHAR(500)  DEFAULT NULL,
  `create_by`       BIGINT        DEFAULT NULL,
  `create_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`       BIGINT        DEFAULT NULL,
  `update_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`         TINYINT       DEFAULT 0,
  `tenant_id`       BIGINT        DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_sal_order_bill_no` (`bill_no`, `deleted`),
  KEY `idx_sal_order_customer` (`customer_id`),
  KEY `idx_sal_order_date` (`bill_date`),
  KEY `idx_sal_order_status` (`bill_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单';

DROP TABLE IF EXISTS `sal_order_detail`;
CREATE TABLE `sal_order_detail` (
  `id`            BIGINT        NOT NULL AUTO_INCREMENT,
  `order_id`      BIGINT        NOT NULL,
  `line_no`       INT           DEFAULT 0,
  `product_id`    BIGINT        NOT NULL,
  `product_code`  VARCHAR(64)   DEFAULT NULL,
  `product_name`  VARCHAR(128)  DEFAULT NULL,
  `spec`          VARCHAR(128)  DEFAULT NULL,
  `unit_id`       BIGINT        DEFAULT NULL,
  `unit_name`     VARCHAR(32)   DEFAULT NULL,
  `qty`           DECIMAL(18,4) NOT NULL DEFAULT 0,
  `price`         DECIMAL(18,4) DEFAULT 0,
  `amount`        DECIMAL(18,4) DEFAULT 0,
  `tax_rate`      DECIMAL(8,2)  DEFAULT 13.00,
  `tax_amount`    DECIMAL(18,4) DEFAULT 0,
  `amount_tax`    DECIMAL(18,4) DEFAULT 0,
  `out_qty`       DECIMAL(18,4) DEFAULT 0,
  `return_qty`    DECIMAL(18,4) DEFAULT 0,
  `batch_no`      VARCHAR(64)   DEFAULT NULL,
  `remark`        VARCHAR(255)  DEFAULT NULL,
  `create_by`     BIGINT        DEFAULT NULL,
  `create_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`     BIGINT        DEFAULT NULL,
  `update_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`       TINYINT       DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_sal_od_order` (`order_id`),
  KEY `idx_sal_od_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单明细';

-- 4.2  销售出库
DROP TABLE IF EXISTS `sal_delivery`;
CREATE TABLE `sal_delivery` (
  `id`              BIGINT        NOT NULL AUTO_INCREMENT,
  `bill_no`         VARCHAR(32)   NOT NULL COMMENT '出库单号: CKP+yyyyMMdd+0001',
  `bill_date`       DATE          NOT NULL,
  `order_id`        BIGINT        DEFAULT NULL,
  `order_no`        VARCHAR(32)   DEFAULT NULL,
  `customer_id`     BIGINT        NOT NULL,
  `customer_name`   VARCHAR(128)  DEFAULT NULL,
  `warehouse_id`    BIGINT        NOT NULL,
  `area_id`         BIGINT        DEFAULT NULL,
  `salesman_id`     BIGINT        DEFAULT NULL,
  `salesman_name`   VARCHAR(64)   DEFAULT NULL,
  `bill_type`       VARCHAR(32)   DEFAULT 'NORMAL' COMMENT 'NORMAL/RETURN/PICKING',
  `total_qty`       DECIMAL(18,4) DEFAULT 0,
  `total_amount`    DECIMAL(18,4) DEFAULT 0,
  `discount_amount` DECIMAL(18,4) DEFAULT 0,
  `tail_amount`     DECIMAL(18,4) DEFAULT 0,
  `tax_amount`      DECIMAL(18,4) DEFAULT 0,
  `total_amount_tax` DECIMAL(18,4) DEFAULT 0,
  `received_amount` DECIMAL(18,4) DEFAULT 0,
  `cost_amount`     DECIMAL(18,4) DEFAULT 0 COMMENT '出库成本总额',
  `profit_amount`   DECIMAL(18,4) DEFAULT 0 COMMENT '毛利',
  `delivery_date`   DATE          DEFAULT NULL,
  `address`         VARCHAR(255)  DEFAULT NULL,
  `phone`           VARCHAR(20)   DEFAULT NULL,
  `bill_status`     VARCHAR(32)   DEFAULT 'DRAFT',
  `remark`          VARCHAR(500)  DEFAULT NULL,
  `create_by`       BIGINT        DEFAULT NULL,
  `create_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`       BIGINT        DEFAULT NULL,
  `update_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`         TINYINT       DEFAULT 0,
  `tenant_id`       BIGINT        DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_sal_delivery_bill_no` (`bill_no`, `deleted`),
  KEY `idx_sal_delivery_customer` (`customer_id`),
  KEY `idx_sal_delivery_date` (`bill_date`),
  KEY `idx_sal_delivery_order` (`order_id`),
  KEY `idx_sal_delivery_status` (`bill_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售出库单';

DROP TABLE IF EXISTS `sal_delivery_detail`;
CREATE TABLE `sal_delivery_detail` (
  `id`            BIGINT        NOT NULL AUTO_INCREMENT,
  `delivery_id`   BIGINT        NOT NULL,
  `line_no`       INT           DEFAULT 0,
  `order_detail_id` BIGINT      DEFAULT NULL,
  `product_id`    BIGINT        NOT NULL,
  `product_code`  VARCHAR(64)   DEFAULT NULL,
  `product_name`  VARCHAR(128)  DEFAULT NULL,
  `spec`          VARCHAR(128)  DEFAULT NULL,
  `unit_id`       BIGINT        DEFAULT NULL,
  `unit_name`     VARCHAR(32)   DEFAULT NULL,
  `qty`           DECIMAL(18,4) NOT NULL DEFAULT 0,
  `price`         DECIMAL(18,4) DEFAULT 0,
  `amount`        DECIMAL(18,4) DEFAULT 0,
  `tax_rate`      DECIMAL(8,2)  DEFAULT 13.00,
  `tax_amount`    DECIMAL(18,4) DEFAULT 0,
  `amount_tax`    DECIMAL(18,4) DEFAULT 0,
  `cost_price`    DECIMAL(18,4) DEFAULT 0,
  `cost_amount`   DECIMAL(18,4) DEFAULT 0,
  `batch_no`      VARCHAR(64)   DEFAULT NULL,
  `location_id`   BIGINT        DEFAULT NULL,
  `location_name` VARCHAR(64)   DEFAULT NULL,
  `sn_no`         VARCHAR(128)  DEFAULT NULL,
  `remark`        VARCHAR(255)  DEFAULT NULL,
  `create_by`     BIGINT        DEFAULT NULL,
  `create_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`     BIGINT        DEFAULT NULL,
  `update_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`       TINYINT       DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_sal_dd_delivery` (`delivery_id`),
  KEY `idx_sal_dd_product` (`product_id`),
  KEY `idx_sal_dd_batch` (`batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售出库明细';

-- 4.3  销售退货
DROP TABLE IF EXISTS `sal_return`;
CREATE TABLE `sal_return` (
  `id`              BIGINT        NOT NULL AUTO_INCREMENT,
  `bill_no`         VARCHAR(32)   NOT NULL,
  `bill_date`       DATE          NOT NULL,
  `source_delivery_id` BIGINT     DEFAULT NULL,
  `customer_id`     BIGINT        NOT NULL,
  `customer_name`   VARCHAR(128)  DEFAULT NULL,
  `warehouse_id`    BIGINT        NOT NULL,
  `total_qty`       DECIMAL(18,4) DEFAULT 0,
  `total_amount`    DECIMAL(18,4) DEFAULT 0,
  `tax_amount`      DECIMAL(18,4) DEFAULT 0,
  `total_amount_tax` DECIMAL(18,4) DEFAULT 0,
  `bill_status`     VARCHAR(32)   DEFAULT 'DRAFT',
  `remark`          VARCHAR(500)  DEFAULT NULL,
  `create_by`       BIGINT        DEFAULT NULL,
  `create_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`       BIGINT        DEFAULT NULL,
  `update_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`         TINYINT       DEFAULT 0,
  `tenant_id`       BIGINT        DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_sal_return_bill_no` (`bill_no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售退货单';

DROP TABLE IF EXISTS `sal_return_detail`;
CREATE TABLE `sal_return_detail` (
  `id`            BIGINT        NOT NULL AUTO_INCREMENT,
  `return_id`     BIGINT        NOT NULL,
  `product_id`    BIGINT        NOT NULL,
  `product_code`  VARCHAR(64)   DEFAULT NULL,
  `product_name`  VARCHAR(128)  DEFAULT NULL,
  `spec`          VARCHAR(128)  DEFAULT NULL,
  `unit_id`       BIGINT        DEFAULT NULL,
  `unit_name`     VARCHAR(32)   DEFAULT NULL,
  `qty`           DECIMAL(18,4) NOT NULL DEFAULT 0,
  `price`         DECIMAL(18,4) DEFAULT 0,
  `amount`        DECIMAL(18,4) DEFAULT 0,
  `tax_rate`      DECIMAL(8,2)  DEFAULT 13.00,
  `tax_amount`    DECIMAL(18,4) DEFAULT 0,
  `amount_tax`    DECIMAL(18,4) DEFAULT 0,
  `batch_no`      VARCHAR(64)   DEFAULT NULL,
  `remark`        VARCHAR(255)  DEFAULT NULL,
  `create_by`     BIGINT        DEFAULT NULL,
  `create_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`     BIGINT        DEFAULT NULL,
  `update_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`       TINYINT       DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_sal_rd_return` (`return_id`),
  KEY `idx_sal_rd_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售退货明细';

-- 4.4  销售报价
DROP TABLE IF EXISTS `sal_quotation`;
CREATE TABLE `sal_quotation` (
  `id`              BIGINT        NOT NULL AUTO_INCREMENT,
  `bill_no`         VARCHAR(32)   NOT NULL,
  `bill_date`       DATE          NOT NULL,
  `customer_id`     BIGINT        NOT NULL,
  `customer_name`   VARCHAR(128)  DEFAULT NULL,
  `expire_date`     DATE          DEFAULT NULL,
  `total_qty`       DECIMAL(18,4) DEFAULT 0,
  `total_amount`    DECIMAL(18,4) DEFAULT 0,
  `tax_amount`      DECIMAL(18,4) DEFAULT 0,
  `total_amount_tax` DECIMAL(18,4) DEFAULT 0,
  `bill_status`     VARCHAR(32)   DEFAULT 'DRAFT',
  `remark`          VARCHAR(500)  DEFAULT NULL,
  `create_by`       BIGINT        DEFAULT NULL,
  `create_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`       BIGINT        DEFAULT NULL,
  `update_time`     DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`         TINYINT       DEFAULT 0,
  `tenant_id`       BIGINT        DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_sal_quotation_bill_no` (`bill_no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售报价单';

DROP TABLE IF EXISTS `sal_quotation_detail`;
CREATE TABLE `sal_quotation_detail` (
  `id`            BIGINT        NOT NULL AUTO_INCREMENT,
  `quotation_id`  BIGINT        NOT NULL,
  `product_id`    BIGINT        NOT NULL,
  `product_code`  VARCHAR(64)   DEFAULT NULL,
  `product_name`  VARCHAR(128)  DEFAULT NULL,
  `spec`          VARCHAR(128)  DEFAULT NULL,
  `unit_id`       BIGINT        DEFAULT NULL,
  `unit_name`     VARCHAR(32)   DEFAULT NULL,
  `qty`           DECIMAL(18,4) NOT NULL DEFAULT 0,
  `price`         DECIMAL(18,4) DEFAULT 0,
  `amount`        DECIMAL(18,4) DEFAULT 0,
  `tax_rate`      DECIMAL(8,2)  DEFAULT 13.00,
  `tax_amount`    DECIMAL(18,4) DEFAULT 0,
  `amount_tax`    DECIMAL(18,4) DEFAULT 0,
  `remark`        VARCHAR(255)  DEFAULT NULL,
  `create_by`     BIGINT        DEFAULT NULL,
  `create_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`     BIGINT        DEFAULT NULL,
  `update_time`   DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`       TINYINT       DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_sal_qd_quotation` (`quotation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售报价明细';

-- 4.5  收款单
DROP TABLE IF EXISTS `sal_receipt`;
CREATE TABLE `sal_receipt` (
  `id`             BIGINT        NOT NULL AUTO_INCREMENT,
  `bill_no`        VARCHAR(32)   NOT NULL,
  `bill_date`      DATE          NOT NULL,
  `customer_id`    BIGINT        NOT NULL,
  `customer_name`  VARCHAR(128)  DEFAULT NULL,
  `pay_type`       VARCHAR(32)   DEFAULT 'CASH',
  `bank_account`   VARCHAR(64)   DEFAULT NULL,
  `amount`         DECIMAL(18,4) NOT NULL DEFAULT 0,
  `source_bill_type` VARCHAR(32) DEFAULT 'SAL_DELIVERY' COMMENT 'SAL_DELIVERY/SAL_ORDER',
  `source_bill_id` BIGINT        DEFAULT NULL,
  `source_bill_no` VARCHAR(32)   DEFAULT NULL,
  `bill_status`    VARCHAR(32)   DEFAULT 'DRAFT',
  `remark`         VARCHAR(500)  DEFAULT NULL,
  `create_by`      BIGINT        DEFAULT NULL,
  `create_time`    DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_by`      BIGINT        DEFAULT NULL,
  `update_time`    DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`        TINYINT       DEFAULT 0,
  `tenant_id`      BIGINT        DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_sal_receipt_bill_no` (`bill_no`, `deleted`),
  KEY `idx_sal_receipt_customer` (`customer_id`),
  KEY `idx_sal_receipt_date` (`bill_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售收款单';

